
INSERT INTO `categories` (`name`) VALUES
('A la poubelle'),
('En attente'),
('Voyages'),
('Education et Enseignement'),
('Guide de Tahiti'),
('Economie et Investissement'),
('Administration'),
('Sports '),
('Hôtels et Tourisme'),
('Journaux et TV'),
('Produits locaux'),
('Traditions, arts et culture');


INSERT INTO `sites` (`web`, `title`, `description`, `kw`) VALUES
('http://www.tntv.pf', 'Tahiti Nui Télévision - Actualités de Polynésie, informations, vidéos, direct, news, culture, sport ', 'TNTV : L\'info en direct de Tahiti et ses îles, les emissions de TNTV en replay, le guide tv', 'tahiti, télévision, actualités, news, replay, reportage, polynesie, bora bora, info, information, pacifique, tv, télé'),
('http://www.ladepeche.pf', 'La Dépêche de Tahiti | Officiel', 'Bienvenue sur le site de la Dépêche de Tahiti.', ''),
('http://www.tntvreplay.pf', 'Tahiti Nui Télévision - Vidéos en replay, journal, Hiro\'s, news, culture et actualité de Polynésie', 'TNTV Replay - Toutes les vidéos de la Polynésie, événement, culture, sport, informations de Tahiti', 'tahiti, télévision, actualité, news, tv, musique, politique, économie, événement, replay, voyage, jeu, reportage, culture, maohi, polynesie, TNTV, faits divers, sport, société'),
('http://mana.pf', 'Vini Internet', '', ''),
('https://www.tahitimenager.pf', 'Tahiti Menager', 'Num&eacute;ro 1 de l\'&eacute;lectrom&eacute;nager a Tahiti.', 'Tahiti, USB, airlux, bosch, brandt, cong&eacute;lateur, coque, c&acirc;ble, exp&eacute;dition, glem, hotte, iPad, iPhone, lave vaisselle, meuble'),
('https://www.axa.pf', ' AXA Assurances Tahiti – Polynésie : auto, habitation, moto, santé, épargne.', 'A Tahiti depuis 20 ans pour vos assurances auto, assurances habitation, moto, mutuelle santé. Mais aussi les assurances professionnelles et assurances vie. Demandes de devis en ligne. ', 'assurance tahiti, assurance polynésie, assurance auto, assurance habitation , assurance moto, assurance scooter, mutuelle santé, assurance santé'),
('https://www.sg-bdp.pf', 'Accueil &mdash; Banque de Polynésie', '', ''),
('http://www.sejoursdanslesiles.pf', 'Séjours dans les îles !', 'Séjours dans les îles Air Tahiti, tour opérateur de la compagnie Air Tahiti, vous propose des séjours vol + hébergement dans les îles de Polynésie française, en pensions de famille ou en hôtels, à des tarifs attractifs, incluant des réductions sur les vols et des tarifs spéciaux dans les hébergements,  tout au long de l.année. Week ends, bons plans, vacances, promos, nouveautés, ventes flash et prix cassés. A destination des Iles sous le vent, Tuamotu, Marquises, Australes, Gambier, Iles Cook. Spécialiste des îles depuis plus de 20 ans', 'sejoursdanslesiles.pf, sejour dans les iles, sejours dans les iles, sejoursdanslesiles séjour dans les iles, air tahiti sejour dans les iles, séjours dans les iles, sejours dans les iles pf, séjours dans les îles, séjours dans les îles air tahiti, séjour '),
('https://secure.opt.pf', 'WEB CCP', '', ''),
('http://www.sg-bdp.pf', 'Accueil &mdash; Banque de Polynésie', '', ''),
('http://www.fenuadeal.pf', 'Accueil - FenuaDeal.pf', 'Accueil - Petites annonces gratuites à Tahiti et en Polynésie', 'fenuadeal, fenua, deal, petite, annonce, petites annonces, petites annonces tahiti, locfute, gratuit, tahiti, polynesie, acheter, vendre, louer, echanger, achat, vente, location, fute, echange, troc, immobilier, voiture'),
('http://www.opt.pf', 'OPT - OPT - Office des Postes et Télécommunication.', '', ''),
('https://selfcare.mana.pf', 'Gestionnaire de Compte Mana - Gestion de compte', '', ''),
('https://moncomptepro.pf', 'MON COMPTE PRO', 'Permet aux agents gérés par le Vice-rectorat de la Polynésie de consulter leur dossier financier et  leurs duplicatas de bulletins de salaire.', 'Vice-rectorat Polynésie éducation dossier professionnel salaire bulletins duplicata copie personnel enseignant administratif'),
('http://lexpol.cloud.pf', 'Lexpol - Le Service Public de la Diffusion du Droit en Polyn&eacute;sie Fran&ccedil;aise', 'Le service public d\'accès au droit en Polynésie Française', 'JOPF journal officiel polynésie francaise marchés publics annonces juridique gouvernement'),
('http://monvr.pf', 'Vice-rectorat de la Polynésie française', 'Le Vice-rectorat de la Polynésie française est un service déconcentré du ministère de l’Éducation nationale. Représentant du ministre de l’Éducation nationale sur le territoire, le vice-recteur est l’interlocuteur privilégié du ministre de l’Éducation de la Polynésie française', ''),
('https://www.hotel-hibiscus.pf', 'Hôtel Hibiscus : Hôtel - Restaurant deux étoiles à Moorea - Polynésie Française', '', ''),
('http://www.majestictahiti.pf', 'Majestic Tahiti - Pour ceux qui M le cinema', 'Majestic Cinéma, Pour ceux qui M le Cinéma !', 'cinéma, cinema, majestic, tahiti, majestictahiti, majestic tahiti, films, salle, film, polynesie francaise, polynésie française'),
('http://meteo.pf', 'M&eacute;t&eacute;o France - Polyn&eacute;sie Fran&ccedil;aise', '', ''),
('http://www.etahititravel.pf', 'Votre voyage à Tahiti avec le sp&eacute;cialiste local, e-Tahiti Travel', 'Préparez votre voyage avec la première agence de voyage sur Internet installée à Tahiti.  H&ocirc;tels et pensions de famille, voyage en couple ou en famille, vols...', 'Voyage Tahiti, voyages Polynésie, voyage de noces Bora Bora, sÃ©jour tahiti, lune de miel Moorea, voyage plongÃ©e Rangiroa, Fakarava'),
('http://www.chezbiancaetbenoit.pf', 'page d\'accueil de la pension Bianca et Benoît', '', ''),
('https://www.maisondelaculture.pf', ' Maison de la Culture de Tahiti &#8211; Te Fare Tauhiti Nui', 'Site officiel on Maison de la Culture de Tahiti &#8211; Te Fare Tauhiti Nui', ''),
('http://paruvendu.pf', '', '', ''),
('https://www.ftf.pf', 'FTF.PF | Fédération Tahitienne de Football', 'Fédération Tahitienne de Football on FTF.PF', ''),
('http://www.socredo.pf', 'Banque Socredo', '', ''),
('http://www.monoitiki.pf', 'PARFUMERIE TIKI - Officiel -', 'SITE OFFICIEL - Le Mono&iuml; avec la fleur 100% MADE IN TAHITI since 1942 - La Parfumerie Tiki est la 1&egrave;re fabrique de Monoi &agrave; Tahiti, 70 ans de savoir-faire, certifi&eacute;e ISO 9001.', 'Parfumerie Tiki, Monoi Tiki, Tahiti, Monoi, mono&iuml;, huile, massage,  naturel, tiar&eacute;, tiare, coco, cosm&eacute;tique, cr&egrave;me, parfum, Fabricant monoi, Fabricant Tahiti, Producteur monoi, Fleur de Tiare, fournisseur Monoi, Huile naturelle, '),
('https://cas.upf.pf', 'CAS &#8211; Central Authentication Service', '', ''),
('http://www.pacificplaza.pf', 'Pacific Plaza | Pacific Plaza le nouveau centre commercial situé à Faa&#039;a', 'Découvrez un centre commercial qui comprend notamment un hypermarché dernière génération. Carrefour - Restauration - Boutiques - Services - Espace client', 'centre commercial, pacific plaza, restauration, boutiques, evenements, shopping, achat, '),
('https://www.ocsd.pf', 'archives en ligne', '', ''),
('https://www.isepp.pf', 'Accueil - ISEPP.pf', '', ''),
('http://www.sopadep.pf', 'SOPADEP - Le leader de l\'automobile à Tahiti', 'SOPADEP, le leader de l\'automobile neuve à Tahiti. SOPADEP OCCASIONS est la solution si vous souhaiter acheter une voiture d\'occasion en Polynésie française.', 'sopadep, peugeot, mitsubishi, porsche, hyundai, opel, chevrolet, bmw, mini, mini cooper, isuzu, chery, gwm, great wall motors, volvo, indeco, hyster, iveco, atlas copco, peinture sikkens, sikkens, voiture, acheter une voiture, acheter un vehicule, acheter'),
('http://petitesannonces.pf', 'Les petites annonces polyn&eacute;siennes - Annonces &agrave; Tahiti en Polyn&eacute;sie', '', ''),
('http://oecpf.pf', 'OECPF - ORGANISATION DES EXPERTS COMPTABLES DE POLYNESIE FRANCAISE', '', 'organisation, experts, comptable, polynesie francaise, polynésie, française, tahiti, auditpac, audit, expertise globale, conseil, évaluation, consolidation, gestion'),
('https://elearning.airtahitinui.pf', 'Air Tahiti Nui - Site E Learning', '', ''),
('https://www.service-public.pf', 'Net.pf ', 'Portail du service publique de l\'administration de la Polynésie française, trouvez ici les réponses à vos questions (impôts, formulaires, santé...).', ''),
('http://www.olympiquedepirae.pf', 'Accueil - OLP Natation', '', ''),
('http://www.optic2000-tahiti.pf', 'Optic 2000 Tahiti | Lunettes &amp; Verres correcteurs', 'Achetez vos lunettes et lentilles de contact à Tahiti. Notre équipe d&#039;opticiens vous accueille en boutique avenue du Maréchal Foch et à Mamao.', ''),
('http://mail.mana.pf', 'Vinimail', '', ''),
('http://www.electrotahiti.pf', 'Electro Tahiti', 'ELECTRO TAHITI : Représentant et distributeur de la marque WHIRLPOOL en Polynésie Française depuis 1973.', 'Machine à laver à Tahiti, Electro Tahiti, frigo tahiti, électroménager tahiti, dépannage tahiti, machine à laver tahiti, lave vaisselle tahiti, whirlpool tahiti, frigidaire tahiti, lave linge tahiti, four tahiti'),
('http://www.raira-lagon.pf', 'Raira Lagon Hotel ', 'Le Raira Lagon Hotel Restaurant vous accueille dans le cadre convivial et intimiste d\'un jardin de 9 000m², au bord du Lagon de Rangiroa. 10 Fare (bungalows) entre tradition et modernité. ', 'hotel rangiroa, hotel familial rangiroa, hotel tuamotu, pension rangiroa, pension tuamotu, hebergement rangiroa, hotel de charme rangiroa polynésie, séjour lune de miel rangiroa, honey moon rangiroa, hébergement plongée rangiroa, hebergement tuamotu, hote'),
('https://secure.banque-tahiti.pf', 'Banque de Tahiti', '', ''),
('http://www.rotui.pf', 'Rotui. Tout le plaisir du fruit', 'Rotui a vu le jour suite au regroupement en coop', 'Rotui, Brasserie de Tahiti, Fruits, Excellence, Plaisir, Top'),
('https://www.tiarefm.pf', 'Tiare FM - Le rythme des &icirc;les | Le rythme des îles', '', ''),
('http://www.education.pf', 'Ministère de l&#039;Education et de l&#039;enseignement supérieur &#8211; Direction Générale&lt;br/&gt;de l&#039;Education et des enseignements', 'Ministère de l\'Education et de l\'enseignement supérieur - Tahiti', ''),
('https://www.radio1.pf', 'Radio 1 Tahiti - Actualités, infos, événements et news de Tahiti', 'Le journal multimédia de la première radio FM de Tahiti. L\\&#039;actualité de la Polynésie : direct, infos, replay, podcasts, news, images de Tahiti et ses îles', 'Radio 1, Tahiti, Polynésie, actu, actus, actualité, actualités, info, infos, fenua, radio, French Polynesia, news, évènements, journal, multimédia, première radio, direct, replay, podcasts, images de Tahiti et ses îles, émissions'),
('https://www.poema.pf', 'Poe-ma insurances', 'Courtier d\'assurances en Polynésie Française', ''),
('https://my.vodafone.pf', 'E-Care', '', ''),
('http://www.chpf.pf', 'ACCUEIL', 'Nouveau site du CHPf', ''),
('https://secur.banque-tahiti.pf', 'Redirection vers le service de banque en ligne TiareNet', '', ''),
('https://www.tefenua.gov.pf', 'Te Fenu@ Mobile', 'Cartographie de la Polynésie française', 'SIG, carte, cartographie, Polynésie française, Tahiti, Bora Bora, Moorea, Rangiroa, Fakarava, Tetiaroa, Marquises, Gambier, Australe, Tuamotu'),
('https://agence.edt.pf', 'Accueil - Agence en ligne EDT', '', ''),
('https://www.tikivillage.pf', 'Tiki Village | TIKI VILLAGE', 'Découvrez l\'authenticité polynésienne au Tiki Village de Moorea dans les mers du Sud, au fond de la Polynésie française', 'tiki village, moorea, wedding, mariage, tahiti, polynesian, tradition, danse polynesienne'),
('http://lvdl.pf', 'Accueil - Radio LVDL', 'Radio LVDL', 'radio'),
('http://www.maupitivillage.pf', 'Maupiti Village', '', ''),
('https://www.espadon.upf.pf', 'Espadon : La plateforme pédagogique de l\'UPF', 'Espadon est la plateforme pédagogique de l\'Université de la Polynésie Française basée sur le LMS Moodle', 'moodle, Espadon'),
('https://www.activ-result.pf', 'ACTIV\'RESULT - Organisme de formation professionnelle à Tahiti', 'Leader en formation professionnelle et en conseil, Activ\'Result se met au service de la performance de votre entreprise.', 'activ\'result, formation professionnelle, consulting, coaching, tahiti, activ result papeete, formation tahiti'),
('http://www.pensiondelaplage.pf', 'Pension de la plage', 'Situé sur la côte Ouest de Tahiti en Polynésie Française, notre petit hôtel familial vous propose l\'accueil chaleureux et les prix avantageux d\'une pension avec tous les services d\'un hôtel.', 'hébergement,gîte,gite,gîtes,gite,hôtel,hotel,pension,bed&breakfast,tahiti,punaauia,papeete,faa\'a,polynésie,studio,chambre,room,réservation,booking,plage'),
('http://www.sefi.pf', 'SEFI - Accueil', '', ''),
('http://pensionlindaraivavae.pf', 'Pension chez Linda', '', ''),
('http://www.ivea.pf', 'Accueil', '', ''),
('https://ecrew.airtahitinui.pf', '', '', ''),
('http://apuradapair.pf', 'APURAD', 'APURAD, Association Polyn', 'dialyse, hemodialyse, peritoneale, insuffisance reinale,tahiti,association,polynesie'),
('http://www.thisse.pf', 'GROUPE THISSE myhomeintahiti, Papeete', 'GROUPE THISSE myhomeintahiti, Papeete', ''),
('http://www.cliniquepaofai.pf', '', '', ''),
('http://www.manao.pf', 'Mana\'o Tahiti - Premier Rhum pur canne distillé et embouteillé à Tahiti', 'Issu de la canne à sucre Otaïti, le rhum Mana’o Tahiti est le fruit d’un travail artisanal alliant respect de la tradition et modernité.', 'manao, tahiti, rhum, brapac, pure canne'),
('http://farevanaa.pf', 'Acad&eacute;mie Tahitienne - Fare V&#257;na\'a', '', ''),
('http://www.farepeaiti.pf', 'Sejour hotel Polynesie  - Sejour hotel Polynesie - Fare Pea Iti - Tahaa - Hébergements -Table d&#039;hôtes', 'Sejour hôtel Polynesie : Fare Pea Iti vous propose un séjour Polynésie. Passez vos vacances  dans un lieu paradisiaque, unique et inoubliable. FARE et TABLE D', ''),
('http://www.sipa.pf', 'SIPA Papeete &amp; Taravao - Meubles, Electromenager, Mobilier de bureau', '', ''),
('http://www.amouy.pf', 'Amouy, le specialiste du portail automatique et volets roulants', 'Le spécialiste des portails automatiques et des volet roulant à Tahiti.  installation de portails automatiques, volets roulant, toits ouvrants, grilles de sécurité, portes blindées, dalles décoratives, aménagements de vehicules, roulottes.  Basée à Tahiti, Polynésie francaise, professionnel de qualités au services des entreprises et des particuliers.', 'Le spécialiste des portails automatiques et des volet roulant à Tahiti.installation de portails automatiques, volets roulant, toits ouvrants, grilles de sécurité, portes blindées, dalles décoratives, aménagements de vehicules, roulottes.Basée à Tahiti, Po'),
('http://www.herve-materiaux.pf', 'Herve Materiaux - Materiaux bois construction Polynesie', 'Herve Materiaux - Pour votre agencement interieur ou exterieur, plusieurs choix de decks, de panneaux melamines, de portes et de bois exotiques !', 'Bois, Bois Tahiti, amenager, construire, decks, fare, materiaux'),
('http://www.cgf.pf', 'Le CGF', 'Le CGF, Centre de Gestion et de Formation', ''),
('https://www.socms.pf', 'Connexion à SOCMS', '', ''),
('http://hyperbrico.pf', 'HYPER BRICO - HYPER BRICO', 'Votre grande surface de bricolage', 'Bricolage,Outillage,Décoration,Jardin,Quincaillerie,Bois,Sanitaire,Electricité'),
('https://monmailpro.pf', 'AMEL OUVERT MOBILE', '', ''),
('http://www.orp.pf', 'Observatoire des requins de Polynesie - Accueil', '', ''),
('http://pos.pf', 'POS | Accueil', 'Entreprise de travaux sous-marins et maritimes basée à Tahiti, présente en Polynésie française depuis plus de 25 ans.', 'travaux maritimes,travaux sous-marins,travaux nautiques,faisceaux,adduction,diagnostics,mesures,mouillages,ancrages,ancrages écologiques,dynamitage,renflouage,levage sous-marin,oxydécoupe,soudure sous-marine,travaux Tahiti,dragage,travaux Polynésie,plongé'),
('http://www.pirae.pf', '    Ville de Pirae | Entre mer et montagne, la ville de Pirae avance  ', ' | Entre mer et montagne, la ville de Pirae avance', ''),
('http://www.waterair.pf', 'piscine tahiti - Waterair', '', ''),
('http://www.pacificcycles.pf', 'PACIFIC CYCLES TAHITI', 'PACIFIC CYCLES TAHITI : Vente et r&eacute;paration de v&eacute;lo en Polyn&eacute;sie', 'cycles tahiti, cyle polyn&eacute;sien, v&eacute;lo tahiti, vtc tahiti, vtt tahiti, velo de course tahiti'),
('http://www.pacific-image.pf', 'Pacific-image', 'Pacific-image est une maison d\'édition de cartes postales, calendriers, posters... montrant des paysages, portraits et scènes de Tahiti et ses îles, en Polynésie française.', 'pacific-image, pacifique, polynesie, polyn&eacute;sie, oceanie, oc&eacute;anie, tahiti, bora bora, moorea, lagon, ile, &icirc;le, paradis, paradisiaque, image, images, photo, photos'),
('http://www.vini.pf', 'Vini', '', ''),
('http://www.oralafibre.pf', 'Ora | La fibre', '', ''),
('http://www.cps.pf', 'Caisse de Prévoyance Sociale | Te Fare Turuutaa', '', ''),
('http://hawaikinuivaa.pf', 'Accueil', '', ''),
('http://www.idkit.pf', 'Id\'kit', 'ID\'KIT TAHITI, agencement sur mesure de cuisines, dressings, placards, salles de bain. Fabrication sur place, produit d\'origine allemande...', 'Tahiti cuisine, Tahiti placard, menuiserie Tahiti, Tahiti dressing, Tahiti salle de bain, Tahiti Bain, Tahiti agencement, Tahiti meuble, Idkit Tahiti'),
('http://www.eauroyale.pf', 'Eau Royale, naturellement pure | Eau Royale, naturellement pure', '', ''),
('http://math.pf', 'maths.pf - Accueil', 'Site académique des Mathématiques en Polynésie Française', 'mathématiques, maths, math, collège, lycée, CETAD, Polynésie, vice-rectorat, DGEE, programme, dnb, pro, ressources, tice, algorithmique, tpe, mps, isn, ccf, investigation, démarche, site, officiel, texte, formation, institutionnel, activité, thème, niveau'),
('http://www.environnement.pf', 'Direction de l\'Environnement |', '', ''),
('http://www.tahiti-tourisme.pf', 'Tahiti et ses îles - Site officiel de Tahiti Tourisme - Tahiti Tourisme', ' 	', ''),
('https://www.tntvreplay.pf', 'Tahiti Nui Télévision - Vidéos en replay, journal, Hiro\'s, news, culture et actualité de Polynésie', 'TNTV Replay - Toutes les vidéos de la Polynésie, événement, culture, sport, informations de Tahiti', 'tahiti, télévision, actualité, news, tv, musique, politique, économie, événement, replay, voyage, jeu, reportage, culture, maohi, polynesie, TNTV, faits divers, sport, société'),
('http://www.temaranui.pf', 'Te Mara Nui - Plonger &agrave; Raiatea', 'Te Mara Nui Plongée est un club de plongée basé à Raiatea en Polynésie française. Réservez dès à présent vos plongées pour découvrir la faune et la flore locales aux côtés de Floriane.', 'Plonger à raiatea, club de plongée, raiatea'),
('http://www.technival.pf', 'Technival', 'Protéger l’environnement, garantir un développement durable, préserver l’état du fenua que nous laisserons à nos enfants font partie des préoccupations croissantes de plus en plus de polynésiens. ', ''),
('https://resu.lam.pf', 'Serveur de r&eacute;sultats', '', ''),
('http://www.villagedenfantssos.pf', 'SOS Village d&#039;enfants', '', ''),
('http://vodafone.pf', 'Vodafone Polynésie - Accueil', 'Site officiel de Vodafone Polynésie', 'Vodafone, vodafone polynésie, vodafone polynesie francaise, vf pf, vfpf, French Polynesia, Best Offers, vodafone pacific, vodafone pf, vodafone fr, vodafone pacific, vodaphone, vodaphone polynesie, vodaphone pf'),
('http://www.faaa.pf', 'Faa&#039;a | Le site de la mairie de Faa&#039;a', ' | Le site de la mairie de Faa&#039;a', ''),
('http://www.airnewzealand.pf', 'Home - Tahiti Site', '', ''),
('http://www.croixrouge.pf', 'Croix-Rouge française, Délégation de la Polynésie', 'Site Officiel de la Délégation de la Polynésie de la Croix-Rouge française', 'Croix-Rouge française Polynésie Française, Délégation de  la Polynésie, dons Tahiti, croix rouge Papeete, organisation caritative, humanitaire, bénévoles, enfants du fenua, bénévolat tahiti'),
('http://atike-immobilier.pf', 'Bienvenue sur le site de l&#039;agence ATIKE IMMOBILIER TAHITI - Agence Immobilière à Tahiti, Polynésie Française', 'Agence immobilière à Papeete, Tahiti, en Polynésie Française. Toutes transactions dans l&#039;immobilier : vente, location et gestion de tous biens.', 'immobilier tahiti, locations tahiti, ventes appartements tahiti, tahiti immobilier, agence immobilière tahiti, programmes immobiliers tahiti gestions de biens tahiti, commerces en vente à tahiti, appartement en location à tahiti, vente tahiti'),
('http://www.tahitiautocenter.pf', 'Tahiti Auto Center &bull; Location de véhicules de tout type, renseignements et réservation au : 823333', 'L\'agence de location Tahiti Auto Center à Paea, vous propose un large choix de véhicules de tous types, du véhicule de livraison au véhicule utilitaire, en passant par le véhicule familiale de 7 places...', 'tahiti auto center, tahiti auto, location automobile tahiti, location voiture tahiti, location vehicule tahiti, vehicule livraison tahiti, vehicule tahiti, automobile tahiti, voiture tahiti, location peugeot tahiti, location hyundai tahiti, location fiat '),
('http://www.armees-polynesie.pf', 'Forces Armées en Polynésie française', '', ''),
('http://www.mis.pf', ' MIS', '', ''),
('http://www.criobe.pf', 'CRIOBE | Centre de Recherches Insulaires et Observatoire de l’Environnement', '', ''),
('http://www.tahitiititourandsurf.pf', 'Tahiti Iti Tour and Surf : Excursions nautiques, Taxi Boat, Surf Tour à Teahupoo sur la presqu\'ile de Tahiti', '', ''),
('http://www.socimat.pf', 'Groupe SOCIMAT : Socimat + Sotapor + Cuisine Plus.', '', ''),
('http://www.aremiti.pf', 'Aremiti | Compagnie Maritime - Navette Rapide - Tahiti Moorea', '', 'transport maritime, tahiti, moorea, transport, passagers, vehicule, fret'),
('http://www.polynesieinterim.pf', 'Bienvenue', ' ', ''),
('http://mae.pf', 'Bienvenue sur le site de la MAE de Polynésie', 'la MAE de Polynésie, l\'assurance scolaire et extra-scolaire de la maternelle à l\'université pour une protection maximale de vos enfants en cas d\'accident', 'assurance scolaire, assurances scolaires, assurance extra scolaire, assurance extra-scolaire, assurance enfant, assurances enfants, assurance collège, assurance lycée, assurance polynésie, assurance scolaire polynésie, protection scolaire, protection extr'),
('http://www.snuipppf.pf', 'SNUipp de Polynésie française &#8211; Syndicat National Unitaire des instituteurs professeurs des écoles et PEGC', '', ''),
('http://www.pamataihills.pf', 'Pamatai Hills | Votre Domaine Résidentiel de Haut Standing à Tahiti    ', 'Votre Domaine Résidentiel de Haut Standing à Tahiti', ''),
('http://gibii.education.pf', 'Evaluation multi-', '', ''),
('http://www.tahititriathlon.pf', 'La Fédération Tahitienne de Triathlon | Site Officiel triathlon tahiti', '', ''),
('http://www.affaires-foncieres.gov.pf', 'Site de la Direction des affaires foncières', '', ''),
('http://relaismoehau.pf', 'hebergement marquise hiva hoa', 'Découvrez le Relais Moehau, Pension de Famille marquisienne de 8 chambres  situés dans les îles Maquises en Polynésie Française. Un expérience rare et authentique...', 'Hébergement Marquise, Hiva oa, Festival Marquise, Plongée Marquise, pension marquise, Cheval Marquise, activités Marquise, îles marquise, marquise hotel, séjour marquise, hiva oa pension, hotel hiva oa, tahiti, tahiti marquise, polynésie marquise, Jacques'),
('http://www.viti.pf', 'ViTi, fournisseur d\'accès internet, 4G, wimax, Polynésie Française, internet, sans fil', 'Viti fournisseur d’accès Internet en Polynésie Française, vous propose une connexion Internet Nomade ou Fixe grâce à son réseau 4G Wimax. Avec Viti, plus besoin de ligne téléphonique et les frais de mise en service sont gratuits.', 'ViTi, fournisseur d\'accès internet, 4G, wimax, Polynésie Française, internet, sans fil'),
('http://www.rsma.pf', 'RSMA Polynésie française', '', ''),
('http://etabs.education.pf', 'DGEE - Portail établissements', '', ''),
('http://www.crea-passion.pf', 'Crea Passion Tahiti', 'CREA PASSION TAHITI : agence web à Tahiti spécialisé dans la conception web, e-marketing, e-mailing, e-sms, e-marketing viral, location de fichier e-mail en Polynésie Française...', 'crea passion, crea passion tahiti, tahiti web, tahiti internet, agence web tahiti, agence internet tahiti, agence internet polynesien, agence web polynesie, site web tahiti, site internet tahiti, boutique en ligne tahiti, e commerce tahiti, internet tahit'),
('http://aprp.pf', 'Bienvenue aux APRP', 'APRP, L\'entreprise pour la réinsertion des personnes handicapées', 'aprp,APRP'),
('http://www.marquises.pf', 'Les îles Marquises en polynésie française', '', ''),
('http://www.ispf.pf', '  	Institut de la statistique de Polyn&#233;sie fran&#231;aise  ', '', 'ISPF, statistique, Polynésie française'),
('http://www.hotu-vanilla.pf', 'Direct Producteur de Vanille de TAHITI à Raiatea, l\'ile soeur de Tahaa, par la famille TAUATITI plusieurs fois médaillée au CGA de 2010 à 2013.', 'Producteur, préparateur et distributeur de Vanille médaillé d\'Or au Concours Général Agricole 2013 et médaillé d\'Argent au CGA 2012, 2011 et 2010 à Paris catégorie ', 'Vanille, Vanille TAHITI, Vanille tahitienne, Vanille de TAHITI, gousse vanille, gousse de vanille, gousse de TAHITI, Achat vanille, acheter vanille, vente vanille, Conservation Vanille, Vanille sous vide, vanille conservation, Vanille de TAHITI, Vanille m'),
('https://www.snes.pf', 'SNES.PF', '', ''),
('https://www.netfenua.pf', 'NetFenua.pf | Votre portail polynésien', 'Votre portail polynésien on NetFenua.pf', ''),
('http://www.conservatoire.pf', 'Conservatoire artistique de la Polynésie française - Te Fare Upa Rau', 'Le conservatoire artistique de la Polynésie française a pour vocation d’assurer la promotion et la valorisation de la culture artistique ; l\'enseignement théorique et pratique de la musique, du chant, de la danse et des arts plastiques ; la préparation et l\'accès à leur enseignement ; la promotion des danses et des chants polynésiens ; la conservation par la reproduction écrite et mécanique du patrimoine musical polynésien ; la mise en place et la promotion de toutes formations orchestrales ou chorales.', 'conservatoire, classique, traditionnel, tahiti, polynésie, poluynésie française, musique, professeurs, violon, violoncelle, alto, flûte traversière, saxophone, trompette, tuba, piano, orgue, jazz, clarinette, percussions, guitare classique, basse électriq'),
('http://www.dbtahiti.pf', ' DB Tahiti', '', ''),
('http://www.tahitiauto.pf', 'Tahiti Automobiles - Ford - Mercedes-Benz - Smart - Land Rover - Range Rover - Honda - Subaru - BYD - JMC - Komatsu - Accueil', '', ''),
('http://cia.pf', 'Accueil', '', ''),
('http://www.camping-nelson.pf', 'Bienvenue au camping Nelson', 'Le Camping Nelson vous accueilleavec ses plages de sables blanc', 'camping Nelson, camping moorea, camping haapiti, camping tahiti, camping polynesie francaise, camping sable blanc moorea'),
('http://www.laklinicduvelo.pf', 'KLINIC DU VELO TAHITI', 'LKDV (la Klinic du vélo) représentant exclusif de la marque SCOTT en Polynésie Française :  VTT, CYCLE...', 'Vélo Tahiti, Bike Tahiti, Vtt Tahiti, cycle Tahiti, Scott Tahiti, réparation vélo Tahiti, cyclisme Tahiti, velo polynesie vélo de course tahiti, vélo enfant tahiti, velo homme tahiti, velo femme tahiti'),
('http://www.piti.pf', 'Pacifique Informatique et Technologies autour d&#039;Internet - piti.pf', '', ''),
('http://www.tetamanuvillage.pf', 'Fakarava Tetamanu', 'Pension Tetamanu Village à  FAKARAVA en Polynésie. Découvrez notre île préservée classé UNESCO, sable blanc, centre de plongée...', 'fakarava, hebergement fakarava, fakarava plongee, fakarava plonge, pension fakarava, restaurant fakarava, sejour fakarava, hotel fakarava, voyage fakarava, vacance fakarava, fakarava, hebergement fakarava, fakarava plongee, fakarava plonge, pension fakara'),
('http://www.innovation-publique.pf', 'Innovation publique &#8211; Un site utilisant Administrations publiques', '', ''),
('http://tahiti-tourisme.pf', 'Tahiti et ses îles - Site officiel de Tahiti Tourisme - Tahiti Tourisme', ' 	', ''),
('http://www.gazdetahiti.pf', 'Accueil', '', ''),
('http://sogimmo.pf', 'Sogimmo', '', ''),
('https://www.fapf.pf', 'Athlétisme en Polynésie &#8211; FAPF', '', ''),
('http://www.sda.pf', 'SDA | Service Distribution Assistance', 'SDA, distributeur à Tahiti du café Nespresso, thé Kusmi Tea et de l&#039;eau Premium Tahiti. Mise à disposition de distributeurs automatiques, boisson et snack.', ''),
('http://pacificfilms.pf', '', '', ''),
('http://www.terevau.pf', 'Votre navette rapide MOOREA – TAHITI | Terevau', 'Informations, Horaires, Tarifs de votre Votre navette rapide MOOREA &#8211; TAHITI avec le Terevau', ''),
('http://vendome.pf', 'Vendome - Bijouterie Joaillerie', '', ''),
('http://www.nrj.pf', '', '', ''),
('http://www.royalhuahine.pf', 'Royal Huahine H&ocirc;tel | Huahine H&ocirc;tels | H&ocirc;tels de Luxe', 'H&ocirc;tel de Luxe, Royal Huahine site Officiel. Offre 11 bungalows sur pilotis en eaux profondes.', ''),
('http://www.bricogite.pf', 'Bienvenue sur www.bricogite.pf', '', ''),
('http://cma.pf', ' Centre des Métiers d&#039;Art', '', ''),
('http://doceo.pf', 'Accueil', 'Centre de formation professionnelle à Tahiti en Polynésie Française', 'formation,centre,organisme,tahiti, papeete,polynésie,apprendre,tahitien,anglais,espagnol,compta,pain,apprendre le tahitien, apprendre à faire son pain, informatique'),
('http://www.infirmiers-polynesie.pf', 'SILPF (le Syndicat des Infirmiers Libéraux de Polynésie Française )', '', ''),
('http://www.monoidetahiti.pf', 'GIMT', '', ''),
('http://www.gotz.pf', 'Accueil', 'Un artiste, 3 mondes : Gotz l\'artiste peintre, Gotzork et Pitoma', ''),
('http://www.easymarket.pf', 'Accueil | Easy Market', '', ''),
('http://temana-import.pf', 'Accueil - Temana Import', 'Situé à Papeete, TeMana Import est une entreprise de vente et de maintenance pour engins et équipements dans le bâtiment, les travaux publics et agricoles.', 'Tractopelle Tahiti , CASE Tahiti , rague Tahiti , pelle hydraulique Tahiti , excavatrice Tahiti , pelle job Tahiti , broyeur Tahiti , mini-pelle Tahiti , tracteur Tahiti , compresseur Tahiti , groupe électrogène Tahiti , dumper Tahiti , pompe à eau Tahiti'),
('http://www.rotopol.pf', 'Rotopol, le rotomoulage de Polynésie', 'Rotopol, le rotomoulage de Polynésie, fabrication de citernes, cuves, poubelle, bacs, piscines, etc..', 'Rotopol, rotopol, rotomoulage, fabrication, citernes, cuves, assainissement, poubelle, loisirs, bacs, piscines, fosses, stockage, gamme'),
('http://www.ville-papeete.pf', 'Le site officiel de la Ville de Papeete', '', ''),
('http://www.museetahiti.pf', 'Museum of Tahiti and the islands - Te Fare Manaha - HOME', 'NEWS', ''),
('http://www.arue.pf', 'Arue &#8211; Tahiti ', '', ''),
('https://www.tna.pf', 'Tahiti Nui Arena ', 'Polynesian Gaming Association', 'Tahiti Nui Arena'),
('http://www.tahitigraphics.pf', 'Tahiti Graphics', 'Imprimerie Tahiti Graphics : papier à lettres, cartes de visites, dépliants, affiches, enveloppes, blocs-notes, brochures, rapport, autocollants, journaux, factures...', 'impression, tahiti, tahitigraphics, imprimerie, services, papier, lettre, cartes, enveloppes, blocs-note, papeterie, impressions, polynésie, française, devis, fichier'),
('http://www.cfpa.pf', 'CFPA - Accueil', '', ''),
('http://tsp.pf', 'TSP  - Tahiti', 'Depuis près de 30 ans, la société TSP (Tahitienne de Secteur Public) est un des acteurs majeurs du paysage environnemental polynésien.  Leader de la collecte et du traitement des déchets liquides et solides, la TSP est engagée depuis sa création dans la protection de l’environnement, le développement durable et l’amélioration du cadre de vie.', 'TSP,tahiti,propreté,services aux particuliers,services aux entreprises,services aux collectivités,papeete,pirae,entretien,poubelles,centre tri,bac à ordure,sacs poubelle,corbeille,détritus,dégazage,fosses septique,nettoyage,polynesie,polynésienne,propreté'),
('http://messervicesvr.pf', 'Services numériques du Vice-rectorat de Polynésie française', '', ''),
('http://www.mesannonces.pf', 'MesAnnonces.pf | Petites Annonces Tahiti et PF', '', ''),
('http://www.fipasud.pf', 'coge2p: Tahiti, Polynésie Francaise, Investissements, Fiscalité, Social, Aides, Subventions, French Polynesia, Investment, Taxation, Social, Subsidy', '', ''),
('https://clients.vini.pf', 'Vini - Espace clients', '', ''),
('http://www.marquises-hivaoa.org.pf', 'Hiva Oa, comite de tourisme, marquises, polynésie', 'Hiva Oa MArquises Accueil', ' Hiva Oa, hivaoa, Culture, turism, MARQUISES, ILES MARQUISES, Marquesas, French Polynesia, polynésie, ATUONA, lodge, hotel, gauguin, pension, tiki, tourisme '),
('http://www.cameleon.pf', 'La Compagnie du Caméléon - Bienvenue', 'Bienvenue sur le site internet de la Compagnie du Caméléon. Découvrez le programme de nos spectacles, nos créations, le cinéma de plein air, nos formations.', ''),
('http://www.immobilier-jeangerard.pf', 'Immobilier jean gerard - Agence immobiliere installée depuis 32 ans à Tahiti ( Papeete ) en Polynésie Francaise ', 'Agence, Agence immobiliere, agence immobiliere tahiti, Vente appartement Tahiti, vente maison tahiti, location appartement tahiti,', 'immobilier tahiti,agence immobilier tahiti, tahiti immobilier,maison Tahiti, appartement Papeete, polynesie immobilier, polynesie francaise immobilier, immobilier french polynesia, appartement polynesie, appartement tahiti, terrain tahiti,villa tahiti,pro'),
('http://www.fare-hau.pf', 'FARE HAU - Pension de Famille à Tahiti - Petite Hôtellerie - maison d\'hôtes', 'Maison d\'hôtes à tahiti FARE HAU', 'fare hau,chambre d\'hôtes tahiti,pension de famille tahiti,petite hotellerie tahiti, maison d\'hôtes tahiti'),
('http://www.fondsparitaire.pf', 'Formation professionnelle continue |', '', 'droit de tirage individualisé,actualités,savoir'),
('http://www.autorite-concurrence.pf', 'Autorité Polynésienne de la Concurrence', 'Un site utilisant WordPress', ''),
('http://apair.pf', 'APAIR', 'APAIR, votre partenaire polyn', 'assistance respiratoire, apnee du sommeil, aerosoltherapie, aspiration endo tracheale, oxygenotherapie, tracheotomie, ventilation non invasive, insulinotherapie, nutrition enterale, PPC, NEAD, APAIR, association, bpco, tahiti, polynesie, retour a domicile'),
('http://www.photos.tahiti-tourisme.pf', 'Tahiti Tourisme', '', ''),
('http://www.lireenpolynesie.pf', 'Association des éditeurs de Tahiti et des îles | Salon du livre &quot;Lire en Polynésie&quot;', '', ''),
('http://www.soleilsucredetahiti.pf', 'Accueil Soleil Sucré de Tahiti - Institut de relaxation', 'Soleil Sucré de Tahiti. Institut de détente et de relaxation corporelle situé au centre commercial du Lotus à Punaauia, ile de Tahiti – Polynésie Française.  Toute les prestations de soins sont réalisées par du personnel qualifié, compétent, sérieux et expérimenté. L’institut est équipé d’une salle d’hydromassage à sec et de 3 salles de massages. Les équipements sont modernes et de haute technologie. Les produits de soins et ceux réservés à la vente sont 100% naturels.', 'Massage, spa, institut, relaxation, hydromassage, détente, Tahiti, Polynésie Française, soins du corps, soins, gommage, enveloppement, Punaauia, Lotus, spa, soleil, sucre, sultane de saba,'),
('http://www.tahiti-vigiles.pf', 'Page d\'accueil', '', ''),
('http://www.annuaireopt.pf', 'Annuaire OPT - Annuaire OPT - Annuaire Téléphonique Officiel de Polynésie Française', 'Annuaire OPT - Annuaire Téléphonique Officiel de Polynésie Française, Annuaire téléphonique officiel de Polynésie Française', 'annuaire,opt,telephonique,telephone,polynesie,tahiti,pages jaunes,pages blanches,pages,bleues,office des postes et telecommunications,polynesie francaise,annuaireopt,operateur telephonique'),
('http://www.fenuama.pf', 'FENUA MA, le syndicat spécialiste du tri en Polynésie française', 'Bienvenue sur le site de FENUA MA, spécialiste du tri en Polynésie française', ''),
('http://www.edt.pf', 'EDT ENGIE | Electricité de Tahiti', '', ''),
('http://www.rugbyclubdepirae.pf', 'Rugby Club de Pirae - Tahiti - Accueil', ' - Accueil, rugby Tahiti, Rugby, Rugby Club de Pirae - Tahiti, PIRAE, 98716, modifié le : 12/6/2013', ''),
('https://imonly.vini.pf', 'Rechargement Internet Mobile', '', ''),
('http://www.clubavantagestahiti.pf', 'Le 1er programme d\'avantages GRATUIT', 'Le 1er programme d\'avantages GRATUIT et ouvert à tous les résidents de Polynésie Française, le Club Avantages Tahiti vous permet de faire des économies au quotidien. Faites des économies toute l\'année grâce au Club Avantages Tahiti !', 'club avantage; club avantages; bon plan; bons plans; carte avantage promotion; cadeau; promo; occasion; reduc; cadeaux; reduction; reductions;  passeport; gourmand; club dec; bon plan; polynesie; BIG-CE; big ce; carte avantages; lepasseportgourmand; avant'),
('http://www.cagest.pf', 'CAGEST | Réussite TPE', '', ''),
('http://c3p.pf', 'C3P : école de pilotage à Tahiti - baptêmes de l\'air, vols de découverte et formations aéronautiques !', 'Venez découvrir avec nous la Polynésie vue d\'en haut, pour un baptême ou apprendre à piloter ! Vous cherchez une école ou un aéroclub à Tahiti ? C3P est là pour vous !', 'pilotage; aeroclub; aero club; avion; tahiti; papeete; polynésie; aircraft; aviation; location; école; club; flight; school; instruction; instructeur; '),
('http://www.conform.pf', 'Bienvenue | Conform HSCT', '', ''),
('http://www.hinano.pf', 'HINANO OFFICIAL WEBSITE - The beer of Tahiti', '', ''),
('http://agences.opt.pf', 'AGENCES - AGENCES - Le site des agences de l\'OPT', '', ''),
('http://pro.opt.pf', 'PRO - PRO : Site Professionnel de l\'OPT', '', ''),
('http://www.engeco.pf', 'Engeco - Spécialiste de la tôle', 'Engeco, Matériaux de construction, spécialiste de la tôle à Tahiti en Polynésie française', 'Engeco, Matériaux, construction, spécialiste de la tôle, Tahiti, Polynésie française, tole, faa\'a, porte, beton, maison, fer, torsade, brouette'),
('http://www.lebihan.pf', 'Location locaux Tahiti, locatif entreprise Tahiti', 'Location de locaux &agrave; Tahiti (Papate) dans centre commercial / centre d&rsquo;affaire &eacute;cologique. Locaux &agrave; louer pour boutique, restauration, magasin, entreprise : 4600m&sup2; de surfaces commercialisables, 150 places de parking', ''),
('http://www.bylie.pf', '  Bylie', '', ''),
('http://annuaireopt.pf', 'Annuaire OPT - Annuaire OPT - Annuaire Téléphonique Officiel de Polynésie Française', 'Annuaire OPT - Annuaire Téléphonique Officiel de Polynésie Française, Annuaire téléphonique officiel de Polynésie Française', 'annuaire,opt,telephonique,telephone,polynesie,tahiti,pages jaunes,pages blanches,pages,bleues,office des postes et telecommunications,polynesie francaise,annuaireopt,operateur telephonique'),
('http://www.degout.pf', 'Agence immobilière DEGOUT - Tahiti - Accueil', 'Agence Degout : locations ventes en polynésie française à tahiti et moorea d\'appartements de maisons de terrains et d\'immeubles', 'immobilier, tahiti, agence immobilière, tahiti immobilier, bora bora, moorea,french polynesia,appartements,terrain,propriete,defiscalisation,loi girardin,loi flosse,villa,investissements,placement financier,marquesas,atoll, island,papeete,tetiaroa,discoth'),
('http://www.technicool.pf', 'Technicool - Installateur de systèmes de sécurité à Tahiti', 'Installateur à Tahiti en Polynésie Française de systèmes de sécurité, Vidéo surveillance, Contrôle d’accès, Alarmes intrusion, Détection Incendie, Interphone, Sonorisation, Réseaux Informatique, Portails et Automatismes.', 'TAHITI,  POLYNESIE FRANCAISE,  MOOREA,  TECHNICIENS,  QUALITE,  SAV,  24/24,  ALARME,  INTRUSION,  SEPTAM,  ELKRON,  ADETEC,  HONEYWELL,  A2P,  HOMOLOGUE,  DETECTEUR,  SIRENE,  TRANSMETTEUR,  BATTERIE,  INCENDIE,  ESSER,  DETECTEUR DE FUMEE,  ALARME INCEN'),
('http://www.airmoorea.pf', 'Maintenance en cours - Planned downtime', '', ''),
('http://www.tahiti-aeroport.pf', 'Aéroport de Tahiti gestionnaire des aéroports : Tahiti Faa\'a, Bora Bora, Raiatea, Rangiroa. - ', '', ''),
('http://www.vitalcalifornia.pf', 'Vital California &#8211; Votre Bien être : notre priorité!', '', ''),
('http://www.sjs.gov.pf', 'Direction de la Jeunesse et des Sports', '', ''),
('http://www.carrefour.pf', 'Carrefour Tahiti en Polynésie Française', 'Bienvenue à Carrefour Polynésie! Promotions et bons plans vous attendent sur carrefour.pf. Consultez les catalogues et économisez sur vos courses !', ''),
('http://www.oph.pf', 'Office Polynesien de l\'Habitat: Accueil', 'Office polynesien de l\'habitat. Aide au logement - Tahiti - Polynesie - Maison - Logement social - Construction MTR', ''),
('https://employeurs.cps.pf', '', '', ''),
('http://www.nautisport.pf', 'NAUTISPORT - Tout pour la mer', 'Groupe Nautisport Tahiti et Raiatea  Tout l\'équipement nautique pour la pratique des sports de mer sont sur nautisport.pf', 'nautisport, tahiti, raiatea, polynesie, francaise,mer, bateau, moteur, jet ski, sea doo, can am, volvo, peche, suzuki, plongée, evinrude, bauer, beneteau, faugerat, equipement, bateau, marine'),
('http://www.fastprint.pf', 'FASTPRINT - Imprimerie et objets personnalisés', 'Fastprint Papeete, Tahiti, Polynésie Francaise: Impression personnalisée pour vos besoins personnels et professionnels, cartes de visite,carte d', 'Fastprint, Tahiti, papeete, carte de visite, cartes de visite, carte, visite, cartes de visites professionnelles, imprimerie en ligne, imprimerie,   imprimeur, imprimeur en ligne, impression par internet, impression en ligne, impression numérique, impress'),
('http://www.meteo.pf', 'M&eacute;t&eacute;o France - Polyn&eacute;sie Fran&ccedil;aise', '', ''),
('http://www.impot-polynesie.gov.pf', 'Direction des Impots et des Contributions Publiques | Fa\'aterera\'a Titau Tute', '', ''),
('https://ensad.criobe.pf', 'ENSAD &#8211; Plate-forme d&#039;enseignement à distance', '', ''),
('http://bigce.pf', 'BIG-CE Le portail Polyn&eacute;sien des Comit&eacute;s d\'entreprises', 'BIG CE propose des avantages et réductions toute l\'année dans plus de 450 enseignes de Tahiti et ses îles, sur présentation de la carte BIG CE ! Vous pouvez déposer gratuitements des petites annonces. Retrouvez aussi les programmes cinéma de Tahiti et des jeux pour gagner des chèques cadeaux et bons d\'achats.', 'Comité d\'entreprise, ce, big ce, big-ce, bureau d\'information générale des comité d\'entreprise, visites virtuelles, auto, moto, bateau, shopping, evasion, maison, travaux, services, iles, les iles, tahiti, moorea, bora bora, huahine, raiatea, tahaa, maupi'),
('http://www.eag.pf', 'Connexion - EAG', '', ''),
('http://www.dgae.gov.pf', 'Direction Générale des affaires économiques', 'Direction Générale des Affaires Economiques (DGAE)', 'télécharger, véhicule, consommation, publicité, acte, acheter, locataire, propriétaire, immobilier, affaires, bail, prix, habitation, automobile, marchandises, budget, vente, droits, Dgae, Direction générale des affaires économiques, Tahiti, Aides, Polyné'),
('https://www.airtahiti.pf', 'Air Tahiti, la compagnie reliant Tahiti et ses îles - Air Tahiti', 'Site Officiel Air Tahiti - Réservez vos billets d&#039;avion pour vos voyages inter îles en Polynésie française, parcourez nos offres et partez à la découverte de nos magnifiques îles.', ''),
('https://www.obeauty.pf', 'Obeauty Tahiti - Massages / Bien-être / Esthétique - Obeauty', 'TEL: 87.759.750 Massage Polynésien - Soin du corps, Esthétique. Massage Relaxant - Taurumi - Balinais. Epilation, Gommages, Enveloppements, Manucure.', ''),
('http://www.conseildesfemmes.pf', 'Conseil des femmes de Polyn', ' F', 'conseil des femmes,conseil femmes,femmes tahiti,tahiti femmes,vahine tahiti,tahiti vahine,femme battue,femmes battues,association femmes battues,sos femmes,tahiti,conseil,Polyn'),
('http://www.royaltahitien.pf', 'Royal Tahitien | Royal Huahine | Royal Polynesia Tahiti H&ocirc;tels', 'Site Officiel de l\'H&ocirc;tel Royal Tahitien and H&ocirc;tel Royal Huahine, faisant partie de la chaine H&ocirc;teli&egrave;re de Luxe du Royal Polynesia Tahiti.', ''),
('http://www.farevanaa.pf', 'Acad&eacute;mie Tahitienne - Fare V&#257;na\'a', '', ''),
('http://www.punaauia.pf', 'L\'actualité | Punaauia', 'Punaauia est une commune du littoral ouest de Tahiti, située dans les Îles du Vent dans l\'archipel de la Société en Polynésie française. Cette ville essentiellement résidentielle dispose de plusieurs comp', 'Punaauia,Tahiti,Polynésie Française,French-Polynesia,Fenua,Tumahai,Turquem,la mairie,Taapuna,Te Tavake,Tamanu,Outumaoro,Nuuroa,Teruamao,Atiue,Raumanu,Atehi'),
('http://www.tahitipearlbeach.pf', 'Tahiti Pearl Beach Resort | Hôtel | Luxe | Tahiti | Suites | Polynésie | Tahiti Pearl Beach Resort', 'Évadez-vous au Tahiti Pearl Beach Resort, un hotel à Tahiti situé dans le cadre tropical et luxuriant de la plage Lafayette qui s&#039;étend sur 900 mètres. Séjournez en bord de plage dans le seul complexe hôtelier 4* de la Côte Est de Tahiti offrant un confort exceptionnel et une vue spectaculaire sur l&#039;océan.', 'Hôtel | Luxe | Tahiti | Suites | Polynésie'),
('http://www.stages-emplois.upf.pf', ' Actualités Stages emplois', 'Une suite logique à vos études', ''),
('http://www.upf.pf', 'Université de la Polynésie Française', 'Site Web de l&#039;Université de la Polynésie Française : Formations LMD, Vie étudiante, enseignement supérieur', 'upf,université,polynésie,formations,étudiant,enseignement,informatique'),
('http://www.projet-immo.pf', 'Projet Immo | L\'Agence Polynésienne De l\'Immobilier', '', ''),
('http://www.maritime.gov.pf', 'Site de la direction polynésienne des affaires maritimes', '', ''),
('https://mad.ac-polynesie.pf', 'Page de connexion', 'Application de gestion des personnels mis à disposition de la Polynésie française.', ''),
('http://www.cgpme.pf', 'CGPME - Le site des entreprises de Polynésie française: Accueil', 'Accueil, ', ''),
('http://www.sodiva.pf', 'Sodiva | L&#039;automobile en Polynésie | Acheter,financer,louer votre voiture', 'Sodiva est un groupe automobile en Polynésie. Nos concessions vendent des voitures neuves et d&#039;occasion, assurent l&#039;entretien et la réparation, le SAV.', ''),
('http://observatoire.criobe.pf', 'Observatoire CRIOBE - Wiki | Welcome', '', ''),
('http://www.officeone.pf', 'Office ONE - Office PRO - c\'est tout pour le bureau !', '', ''),
('http://www.global-patrimoine.pf', 'Global Patrimoine - Gestion de Patrimoine -Tahiti Punaauia (98) - Jérôme GASIOR', '', ''),
('http://www.transports-terrestres.pf', 'Version française - Version française', '', ''),
('http://www.ccism.pf', 'CCISM | Polynésie française |', 'Créer votre business, développer votre entreprise, exporter, vous former, vous informer. La CCISM vous accompagne et vous simplifie la vie d&#039;entrepreneur.', 'entreprise-société-business-entreprendre-développer-créer-exporter-économie-ccism-tahiti-polynésie-former-informer-entrepreneur-créateur'),
('http://www.grepfoc.pf', 'La formation continue en Polynésie française', '', ''),
('http://www.jrcc.pf', 'JRCC Tahiti : Centre de recherche et de sauvetage en mer', 'Le JRCC Tahiti est le centre de surveillance, de recherche et de sauvetage en mer, basé à Papeete sur l’île de Tahiti en Polynésie française.', ''),
('http://groupe.opt.pf', 'Groupe OPT | ACTEUR D&#039;INNOVATION', '', ''),
('http://www.maternelle.education.pf', 'Mission Maternelle', '', ''),
('http://www.generation-what.pf', 'Generation What? – La grande enquête sur les 18-34 ans en Polynésie !', 'Generation What? L&#039;enquête qui fait l&#039;auto-portrait d&#039;une génération : la tienne !', ''),
('http://www.culture-patrimoine.pf', 'Site du service de la culture et du patrimoine', '', 'Fran&#231;ais,English ,Espagnol,Reo maohi'),
('http://www.epugibet.pf', 'entreprise', 'Vente de matériaux de construction - béton - ciment - parpaing - fers à béton - concassés - agrégats - Tahiti Polynésie', ''),
('https://services.cps.pf', 'Caisse de Prévoyance Sociale', '', ''),
('http://www.tahitipearlregatta.org.pf', 'Tahiti Pearl Regatta | La plus grande régate festive du Pacifique insulaire', '', ''),
('https://ipfc10.criobe.pf', 'IPFC10 | The 10th Indo-Pacific Fish Conference, 2-6 October 2017', '', ''),
('http://www.hiroa.pf', '', '', ''),
('http://www.ethik.pf', 'Ethik immobilier / syndic - Accueil', '', ''),
('http://www.vodafone.pf', 'Vodafone Polynésie - Accueil', 'Site officiel de Vodafone Polynésie', 'Vodafone, vodafone polynésie, vodafone polynesie francaise, vf pf, vfpf, French Polynesia, Best Offers, vodafone pacific, vodafone pf, vodafone fr, vodafone pacific, vodaphone, vodaphone polynesie, vodaphone pf'),
('http://www.eps.dep.pf', 'eps1.pf - Education Physique et Sportive du 1er degr&eacute en Polyn&eacute;sie Fran&ccedil;aise', ' eps1.pf - Toutes les informations sur l\'Education Physique et Sportive (EPS1) , les Sorties Scolaires à l\'&eacute;cole primaire et le sport scolaire en Polyn&eacute;sie Fran&ccedil;aise', ' eps1 polynesie, eps1.pf, cssu polynesie, ctssu, usep, usepol, assep, ussp, ascup, epap, dep, sport, sport scolaire, sortie scolaire, aps, tahiti, education, ecole, pedagogie, education, enseignement, enseignant, sante, polynesie '),
('http://www.biosecurite.gov.pf', 'Bios&#233;curit&#233; - Service phytosanitaire', 'Protection des végétaux de polynésie française', 'vegetaux,phytosanitaire'),
('http://www.petitesannonces.pf', 'Les petites annonces polyn&eacute;siennes - Annonces &agrave; Tahiti en Polyn&eacute;sie', '', ''),
('http://www.proscience.pf', 'Accueil - Proscience', '', ''),
('http://www.wedesign.pf', 'Wedesign l\'agence de communication par le web', 'Agence web à Tahiti, Wedesign réalise vos projets de e-communication : site internet, e-commerce, application mobile, réseaux sociaux, jeux, référencement, webmastering', ''),
('http://www.cercledesnageursdepolynesie.pf', 'Cercle des Nageurs de Polynésie', 'Rahiti DE VOS a participé avec son université de l’Utah aux championnats universitaires américain de la conférence « Pac-12 » à Fédéral Way (WA) du 1er au 4', 'Natation,Tahiti,Polynésie,Nageurs'),
('http://www.monfare.pf', 'Mon Fare : toute l\'information sur la construction en Polynésie | Construction à Tahiti | Maison | Décoration | Jardin | Site Communautaire', 'Construction à Tahiti, Maison, Décoration, Jardin : MonFare.pf est le site sommunautaire sur la maison à Tahiti.', ''),
('http://manu.pf', 'ManuSOP Manu - Protection des oiseaux en Polynésie française', 'Depuis sa création, l&#039;association Manu lutte pour la sauvegarde des espèces d&#039;oiseaux sauvages de Polynésie française', '');
INSERT INTO `sites` (`web`, `title`, `description`, `kw`) VALUES
('http://www.anset.pf', 'ANSET Assurances, spécialiste de l&#39;assurance auto, 2 roues et habitation à Tahiti', 'ANSET Assurances, Société de courtage implantée depuis 10 ans en Polynésie disposant de 6 agences sur les îles de Tahiti et Moorea, propose ce qui se fait de mieux en matière d&#39;assurance auto, 2 roues et habitation. Accueil Polynésien, tarifs compétitifs, compétences reconnues.', 'assurance,assurances,assureur,assureurs,garantie,garanties,automobile,auto,voiture,moto,cyclo,scooter,2 roues,polynésie,tahiti,papeete,anset,tarif,prix,devis,scolaire,habitation,multirisque,tous riques,tiers,maison,incendie,vol,accident,sinistre,formule,c'),
('http://www.cesc.pf', 'CESC - Conseil Economique Social et Culturel de la Polynésie française - Actualités', 'Le Conseil économique, social et culturel est la quatrième institution de la Polynésie française. Il s\\\'inscrit comme une complémentarité dans la vie institutionnelle et civile du pays.', 'CESC,conseil,economique,social,culturel,polynésie française,tahiti'),
('http://www.novacom.pf', 'NOVACOM : Agence web tahiti', 'Novacom > Agence web à Tahiti, création de site web, référencement, emailing...', 'agence web tahiti, agence web polynesie, web polynesien, agence internet tahiti, agence internet polynesie, internet tahiti, internet polynésie, novacom, Emailing tahiti, création site web tahiti, site internet tahiti, web tahiti, agence web tahiti, ecomm'),
('http://www.wakeup.pf', 'WAKE UP! - Agence globale de communication, 100% Made in Tahiti !', '', ''),
('http://www.brapac.pf', 'BRAPAC - Importateur et distributeurs de vins, spiritueux et produits alimentaires à Tahiti et en Polynésie française', 'La BRAPAC développe l’importation de produits de consommation de grande qualité et la distribution dans toutes les îles auprès de tous les circuits : détaillants, hypermarchés, hôtellerie, restauration. Ses gammes de vins et spiritueux, de produits alimentaires sont constamment enrichies par des produits nouveaux et innovants, proposés par les grandes marques de renommée internationale.', 'alimentaire, vin, importation, tahiti, polynésie française, pacifique, alcool, distribution, spiritueux'),
('http://www.presidence.pf', 'La Présidence de la Polynésie française', '', ''),
('http://www.creaprint.pf', 'Accueil - Créaprint', 'Dixit, revue éco - Fare, guide de l&#039;habitat - Tamarii, guide des activités - Maitai, guide des restaurants - Moana, guide de la mer - Guide des métiers', ''),
('http://maths.pf', 'maths.pf - Accueil', 'Site académique des Mathématiques en Polynésie Française', 'mathématiques, maths, math, collège, lycée, CETAD, Polynésie, vice-rectorat, DGEE, programme, dnb, pro, ressources, tice, algorithmique, tpe, mps, isn, ccf, investigation, démarche, site, officiel, texte, formation, institutionnel, activité, thème, niveau'),
('http://www.notredamedesanges.pf', 'Notre Dame Des Anges - Tahiti', 'Notre Dame Des Anges - Tahiti', 'collège, college, ecole, école, Tahiti, école tahiti, collège Tahiti, ecole Tahiti, college Tahiti, nda, college nda, collège nda, ecole nda, notre dame des anges'),
('https://www.dgen.pf', 'L&#039;actualité du numérique en Polynésie française - L&#039;actualité du numérique en Polynésie française', 'L&#039;actualité du numérique en Polynésie française', ''),
('http://www.sofidep.pf', 'Sofidep | Société de Financement du Développement de la Polynésie française', 'La SOFIDEP assure une mission publique de développement économique, au service de l\'ensemble des entreprises polynésiennes.', 'sofidep, financement, investissement, cofinancement bancaire, tahiti, polynesie francaise, papeete, réaliser mon projet, création, développement, innovation, développement durable, secteur primaire, pêche, agriculture, entreprenariat, commerce, trésorerie'),
('http://www.matuvu.pf', 'MATUVU &quot;La Première agence de matériel publicitaire à Tahiti&quot;', 'Matuvu est votre spécialiste de la communication imprimée a Tahiti. Elle conçoit et fabrique tout type d’éléments publicitaires, du packaging à la PLV...', 'matuvu tahiti,matuvu,ex,affiche de tahiti,polynesie,francaise,papeete,faaa,auae,materiel,publicitaire,banderole,kakemono,stickers,toile tendue,Cadre,deco,roll-up,affiches,covering,web,site,internet,impression,impressions,support,supports,enseigne,enseigne'),
('http://www.monvr.pf', 'Vice-rectorat de la Polynésie française', 'Le Vice-rectorat de la Polynésie française est un service déconcentré du ministère de l’Éducation nationale. Représentant du ministre de l’Éducation nationale sur le territoire, le vice-recteur est l’interlocuteur privilégié du ministre de l’Éducation de la Polynésie française', ''),
('https://www.upf.pf', 'Université de la Polynésie Française', 'Site Web de l&#039;Université de la Polynésie Française : Formations LMD, Vie étudiante, enseignement supérieur', 'upf,université,polynésie,formations,étudiant,enseignement,informatique'),
('http://www.audifi.pf', 'Audifi (Cabinet comptable ', 'Cabinet comptable ', 'Cabinet comptable '),
('https://www.airnewzealand.pf', 'Air New Zealand - Cheap Flights, Discount Vacations - Official Site', 'Get on board with Air New Zealand for great value flights, fly to New Zealand, Australia, the Pacific Islands and United Kingdom. Direct flights to New Zealand from Los Angeles, San Francisco &amp; Houston', ''),
('http://www.airfrance.pf', 'Air France Site officiel-Billets d\'avion vers Paris, Los Angeles, Europe ', 'Billets pas cher, vols vers Paris,Los Angeles', ''),
('http://www.tikitea.pf', 'Tikitea, votre partenaire hygiène en Polynésie Française - Accueil', 'Tikitea, votre partenaire hygiène en Polynésie Française. Production de papiers, cosmétiques, détergents et sacs plastiques.', 'nettoyage hygiene entretien brosserie tahiti'),
('http://www.axians.pf', 'AXIANS', '- VINCI Energies', ''),
('http://www.c3p.pf', 'C3P : école de pilotage à Tahiti - baptêmes de l\'air, vols de découverte et formations aéronautiques !', 'Venez découvrir avec nous la Polynésie vue d\'en haut, pour un baptême ou apprendre à piloter ! Vous cherchez une école ou un aéroclub à Tahiti ? C3P est là pour vous !', 'pilotage; aeroclub; aero club; avion; tahiti; papeete; polynésie; aircraft; aviation; location; école; club; flight; school; instruction; instructeur; '),
('http://www.rangiroaplongee.pf', 'Rangiroaplongée club de plongée Rangiroa Tuamotus Polynésie', '', ''),
('http://fenuadeal.pf', 'Accueil - FenuaDeal.pf', 'Accueil - Petites annonces gratuites à Tahiti et en Polynésie', 'fenuadeal, fenua, deal, petite, annonce, petites annonces, petites annonces tahiti, locfute, gratuit, tahiti, polynesie, acheter, vendre, louer, echanger, achat, vente, location, fute, echange, troc, immobilier, voiture'),
('http://www.apd.pf', 'HACHETTE PACIFIQUE - Importateur de papeterie, librairie, presse, jouets et jeux de société à Tahiti', 'Hachette Pacifique (APD) est une entreprise spécialisée dans l’importation de papeterie, de librairie, de jouets et jeux de société.', 'hachette, pacifique, papeterie, presse, libriarie, jeux,  importation, tahiti, polynésie française'),
('http://www.bull.pf', '', '', ''),
('http://www.tahitifaahotu.pf', 'Tahiti Fa\'ahotu', 'Tahiti Fa\'ahotu regroupe des entreprises polynésiennes et des organismes de recherche et de formation locaux autour d\'un objectif commun, l\'innovation pour la valorisation des ressources naturelles.', 'Tahiti, Fa\'ahotu, faahotu, organisme, recherche, exploitation, ressources, naturelles, marines, terrestres, renouvelables'),
('http://www.vindetahiti.pf', 'Vin de Tahiti - Domaine Dominique Auroy', 'Nous vous invitons à découvrir ici l\'aventure du vin de Tahiti. Une histoire d\'hommes et de femmes profondément attachés à leur terroir, qu\'ils veulent révéler et partager au travers de vins étonnants, porteurs d\'une identité unique.', 'vin, tahiti, papeete, rangiroa, avatoru, polynesie, tiputa, tuamotu, blanc, rosé, rouge, vigne, raisin, domaine, auroy, dominique, corail, récif, nacarat, moelleux, pacifique, exotique, ampélidacées, polynésien, archipelagoes, vignoble, île, atoll, motu, '),
('http://www.spap.pf', 'SPAP', 'Le site de la condition animale en Polynésie. Adoptions', 'animaux tahiti adoption chien chat spa spap polynesie'),
('http://www.sossuicide.pf', '  Association Sos suicide de Polynésie Française &#8211; Tahiti &#8211; Un message pour la vie', 'Le site sos suicide souhaite aider toute personne en dificulté; personne ayant des idées noires, pensant éventuellement au suicide. Informations déstinées à les familles endeuillées par suicide. Besoin d\'en parler : numéro vert : 444 767 ligne directe. ', 'suicide, tentative de suicide, dépression, idées noires, conduites suicidaires, besoin de parler, mourir, désespoir, désarrois, rupture sentimentale, problèmes familiaux, journée de prévention du suicide, intervention dans les îles, formation, pendaison, '),
('http://www.gsft.pf', 'GROUPEMENT DE SOLIDARITE DES FEMMES DE TAHITI', 'Accueil Groupement de Solidarit', 'Accueil,accueil tahiti,Tahiti,femmes,tahiti femmes,femmes du groupement,solidarit'),
('http://www.bigce.pf', 'BIG-CE Le portail Polyn&eacute;sien des Comit&eacute;s d\'entreprises', 'BIG CE propose des avantages et réductions toute l\'année dans plus de 450 enseignes de Tahiti et ses îles, sur présentation de la carte BIG CE ! Vous pouvez déposer gratuitements des petites annonces. Retrouvez aussi les programmes cinéma de Tahiti et des jeux pour gagner des chèques cadeaux et bons d\'achats.', 'Comité d\'entreprise, ce, big ce, big-ce, bureau d\'information générale des comité d\'entreprise, visites virtuelles, auto, moto, bateau, shopping, evasion, maison, travaux, services, iles, les iles, tahiti, moorea, bora bora, huahine, raiatea, tahaa, maupi'),
('http://www.tep.pf', ' Accueil - TEP', 'Soci&amp;eacute;t&amp;eacute; polyn&amp;eacute;sienne sp&amp;eacute;cialis&amp;eacute;e dans le transport d&#039;&amp;eacute;nergie &amp;eacute;lectrique depuis 1986.', 'TEP,reseau electrique'),
('http://www.ciguatera.pf', 'Accueil ', 'Bienvenue sur le site de la ciguatéra. Vous y trouverez l\'essentiel des informations sur cette intoxication qui touche de plus en plus de régions du monde.', 'Ciguatéra, ciguatéra en polynésie française, symptômes de la ciguatéra, traitements de la ciguatéra'),
('http://www.cardella.pf', 'CLINIQUE CARDELLA', 'Clinique Cardella', 'clinique, cardella, polynésie, polynesie, polynésie française, tahiti'),
('http://www.surf.pf', 'Fédération Tahitienne de Surf', 'Site officiel de la FГ©dГ©ration Tahitienne de Surf', ''),
('http://www.orabusiness.pf', 'Ora Business, opérateur réseau et télécom dédié aux entreprises', 'Ora Business, opérateur réseau et télécom dédié aux entreprises', 'Ora Business, opérateur réseau et télécom dédié aux entreprises'),
('http://www.manhein.pf', 'ETS MANHEIN - TAHITI - Magasin Electroménager à Tahiti - Spécialiste Climatisation Tahiti - SAV', 'Spécialiste de l\'électroménager et de la climatisation à Tahiti depuis 1965. - Magasin électroménager Tahiti - Climatisation Tahiti -  SAV électroménager Tahiti - électroménager tahiti, climatiseur tahiti, clim tahiti, climatisation tahiti, installateur clim tahiti, machine à laver à Tahiti, réfrigérateur tahiti, dépannage tahiti, réparation électroménager tahiti, réparation à domicile tahiti, réparateur tahiti, sav tahiti, machine à laver tahiti, lave vaisselle tahiti, white-westinghouse tahiti, frigidaire tahiti, lave linge tahiti, four tahiti, table de cuisson tahiti, cuisiniere tahiti, cave à vin tahiti, hotte tahiti, congélateur tahiti, micros-ondes tahiti, déshumidificateur tahiti, plaque de cuisson tahiti, induction tahiti', 'électroménager tahiti, climatiseur tahiti, clim tahiti, climatisation tahiti, installateur clim tahiti, machine à laver à Tahiti, réfrigérateur tahiti, dépannage tahiti, réparation électroménager tahiti, réparation à domicile tahiti, réparateur tahiti, sa'),
('http://tetiaroa.pf', 'Luxury Resort in French Polynesia - Home | The Brando', 'The Brando is a luxury resort on French Polynesia&#039;s beautiful private island of Tetiaroa. The resort features 35 villas on white-sand beaches.', ''),
('http://www.artcuisine.pf', 'Accueil - Art Cuisine', 'Art Cuisine: Matériel de cuisine pour les professionnels et les amateurs, équipements de cuisine, chambres froides et buanderie', ''),
('http://www.tahitiguide.pf', 'tahitiguide : Guide et annuaire touristique sur tahiti - voyages, hotels, sejours a tahiti et les iles, Bora bora, Moorea', '', ''),
('http://www.plastiserd.pf', 'Plastiserd (Tahiti) : Emballages et produits plastiques - Accueil', 'PLASTISERD est une entreprise spécialisée dans la fabrication et la distribution d’emballages et de divers articles en matière plastique.', 'Emballages,Vaisselle,Bouteilles,Barquettes,Bâtiment,Travaux de rénovation,Perliculture,Horticulture,Jardin,Plastique,Traiteur,Lambris,PVC,tahiti,polynésie française'),
('http://www.pdjeux.pf', 'LOTO&reg;, SUPER LOTO&reg;, Euro Millions - My Million, Keno Gagnant à vie, JOKER +&reg; - Site de la Pacifique des Jeux', '', ''),
('https://www.net.pf', 'Net.pf ', 'Portail du service publique de l\'administration de la Polynésie française, trouvez ici les réponses à vos questions (impôts, formulaires, santé...).', ''),
('http://www.tahoeraahuiraatira.pf', 'Tahoeraa Huiraatira - Le parti au service du pays', 'Le Tahoeraa Huiraatira est un parti politique autonomiste établi à Tahiti en Polynésie française le 6 mai 1977. Créé et présidé par Mr. Gaston Flosse Sénateur de la Polynésie française. Philosophie : le patriotisme, l\'engagement politique et la reconnaissance du pays.', 'tahoeraa,huiraatira,gaston,flosse,président,tahiti,papeete,assemblée,gouvernement,polynésie,française,sénateur,parti,politique,union,ump,tahitien,loi,autonomie,élection,électeur,fjt,socio pro,élus,fédérations,travail,temaru,tavini'),
('http://www.atvmooreatours.pf', 'Atv Moorea', 'ATV MOOREA TOURS : Randonnée en quad sur l\'île de Moorea en plein coeur du volcan...', 'quad moorea, excursion moorea, quad tahiti, atv moorea, visite moorea, randonnee moorea, moorea, aventure moorea, balade moorea, activite moorea, tahiti quad, quad moorea, excursion moorea, quad tahiti, atv moorea, visite moorea, randonnee moorea, moorea,'),
('http://www.tahitizoom.pf', 'Tahiti Zoom', '', ''),
('http://www.synergence.pf', 'Synergence Communication', 'Agence de communication spécialisée en Evénementiel, Production de spectacle et Activations de marques.', 'synergence, communication, event, tahiti, polynésie, production, spectacle, artiste, soirée, marque, produits, marketing'),
('http://www.hcr987.pf', 'Accueil - Portail de l\'Etat en Polynésie française', 'Les services de l\'État en Polynésie française', 'cms, publish, e-commerce, content management, development framework'),
('http://www.total.pf', 'Total en Polynésie - Accueil particuliers', 'TOTAL POLYNESIE est un réseau de 22 stations services réparties dans sur plusieurs îles de la Polynésie : Tahiti, Moorea, îles sous le vent, îles Marquises, îles Australes.', ''),
('http://www.poecharter.pf', 'Croisières catamaran Tahiti Bora Bora Tuamotu - Poe Charter Tahiti', 'Croisières privées ou à la cabine en catamaran au départ de Tahiti vers les iles sous le vent et les Tuamotu. Location catamaran avec ou sans skipper.', ''),
('http://www.lolita.pf', '[LoLiTa : Logiciels Libres à Tahiti et dans les îles]', 'L&#39;association LoLiTa a pour objet la promotion, l&#39;aide au d&#233;ploiement et le d&#233;veloppement en Polyn&#233;sie fran&#231;aise des logiciels libres, open source et/ou alternatifs en g&#233;n&#233;ral et du syst&#232;me d&#39;exploitation GNU /Linux en particulier. Elle soutient le projet FenuaSoft une compilation de Logiciels Libres cr&#233;&#233;e sur le Fenua, pour le Fenua. Ce projet a pris la forme d&#39;un c&#233;d&#233;rom qui contient 40 logiciels pour PC. En m&#234;me temps, une version est consultable sur internet et h&#233;berg&#233;e &#224; Tahiti. La page d&#39;accueil du site de l&#39;association pr&#233;sente les articles de r&#233;dacteurs b&#233;n&#233;voles de Tahiti et des &#238;les, du plus r&#233;cent au plus ancien. Pour &#234;tre tenu au courant de nos actions vous pouvez vous inscrire &#224; notre lettre d&#39;information ou vous abonner au fil rss. Le logiciel libre c&#39;est une id&#233;e g&#233;n&#233;reuse, des solutions techniques r&#233;alistes et efficaces, un forum local pour poser vos questions simples ou complexes. Ne restez pas seul dans votre coin, soutenez-nous en nous rejoignant ! Recevez de nos nouvelles en vous inscrivant &#224; notre lettre d&#39;information', 'Sur le web,L&#39;association LoLiTa ,L&#39;atelier des linuxiens,D&#233;butants,L&#233;gislation,Le Libre en Polyn&#233;sie,Le Libre ailleurs,test rubrique'),
('http://www.pensionchayantahiti.pf', 'Pension Chayan', 'Une pension de famille ', 'pension, tahiti, polyn'),
('http://www.relaismoehau.pf', 'hebergement marquise hiva hoa', 'Découvrez le Relais Moehau, Pension de Famille marquisienne de 8 chambres  situés dans les îles Maquises en Polynésie Française. Un expérience rare et authentique...', 'Hébergement Marquise, Hiva oa, Festival Marquise, Plongée Marquise, pension marquise, Cheval Marquise, activités Marquise, îles marquise, marquise hotel, séjour marquise, hiva oa pension, hotel hiva oa, tahiti, tahiti marquise, polynésie marquise, Jacques'),
('http://www.pacificompany.pf', 'Sie et Pacific Company', 'PACIFIC COMPANY et SIE DISTRIBUTION &gt; Impression et personnalisation tout support textile &amp; communication par l&#39;objet...', 'textile tahiti, impression tahiti, objet publicitaire tahiti, cadeaux tahiti, broderie tahiti, objet tahiti, sie tahiti, pacific company tahiti, imprimerie tahiti,Porte clés tahiti, Stylos tahiti, Agenda tahiti,Top femme tahiti, casquettes tahiti, t-shirt'),
('http://manaotattoo.pf', 'Tatouages polynésiens / Polynesian tattoo - Mana\'o Tattoo Studio Tahiti', 'Tatouage tahitien, tatouage marquisien, tatouage Polynésien à Papeete Tahiti. Internationally recognized and award winning artists. Polynesian tattoo studio in Papeete Tahiti.  ', 'tatouage polynesien, tatouage marquisien, tatouage tahitien, polynesian tattoo, maquesan tattoo, tahitian tattoo, tatouage, tatau, tamoko, irezumi, polynesian tattoo, tatouage polynesien, award winning tattoo artists, maori, marquisien, tahitien, japonais'),
('http://www.odyssey.pf', 'Odyssey Tahiti !', '', ''),
('http://www.technimarine.pf', 'BIENVENUE CHEZ TECHNIMARINE', 'le chantier naval technimarine, basé à Tahiti, est la reference pour travaux sur les bateaaux, voiliers, monocoques, catamarans, tonier, pour tous types de travaux maritimes,   un chantier a la hauteur de vos esperances', 'chantier nautique, chantier naval, carenage, nautisme, antifouling, travelift, bateaux, bateau, trauvaux maritimes, travaux nautiques,   shipchandler, elevateur bateau, polynesie francaise, tahiti   marina, construction bateaux, quai, polyester, resine ep'),
('http://www.pensionlindaraivavae.pf', 'Pension chez Linda', '', ''),
('http://www.sodispo.pf', 'SODISPO — Design by Red Soyu', 'Design by Red Soyu', ''),
('http://www.lapizzeria.pf', 'L\'apizerria Tahiti - Restaurant Italien', 'Très bel endroit à Tahiti, restaurant climatis&eacute;, bistrot, brasserie, bar, concept original branch&eacute; et savoureux', 'L\'apizzeria,Bistronomie,Tahiti,Restaurant,Incontournable,meilleur, ...'),
('http://salondutourisme.pf', 'Salon du Tourisme - Tahiti Tourisme', 'Découvrez Salon du Tourisme sur le site http://www.tahiti-tourisme.pf/ - Tahiti Tourisme', ''),
('http://www.speedpiscines.pf', 'Speed Piscines', 'Speed Piscines Tahiti &gt; Grand choix d’accessoires, et matériel piscine, en kit, piscines enterré et hors sol et Spa. Systèmes de sécurité, entretien à la carte,dépannage, produits…', 'piscine tahiti, création piscine tahiti, accessoires piscines, matériel piscine tahiti, piscines kit tahiti, piscines enterré tahiti, piscinehors sol tahiti, tahiti Spa. Systèmes de sécurité tahiti piscine, entretien piscine tahiti, dépannage piscine, pro'),
('http://www.pensionopeha.pf', 'pension Opeha', 'Tahiti, pension excursion, travel, pacific, lagoon, lagon, polynesie polynesia', 'pension opeha'),
('http://www.petites-annonces.pf', 'Les petites annonces polyn&eacute;siennes - Annonces &agrave; Tahiti en Polyn&eacute;sie', '', ''),
('http://www.viniboxpro.vini.pf', 'Vinibox PRO - La fibre pour les professionnels', 'Vinibox PRO, l&#039;offre Internet Très Haut Débit dédiée aux professionnels. Profitez des avantages de la fibre : vitesse, simultanéité, performance.', 'Vini, Internet, fibre, Vinibox, box, très haut débit'),
('http://www.sta.pf', 'STA - Société Tahitienne Automobile', 'STA - La Société Tahitienne Automobile est le distributeur des marques Citroën, Kia et Mazda en Polynésie française.', 'sta, citroen, citroën, c1, c2, c3, c4 , citroen picasso, c4 picasso, kia, mazda, kia soul, kia rio, kia picanto, kia cerato, kia sportage, kia sorento, kia mohave, kia k2700, mazda2, mazda3, mazda5, mazda6, mazda bt-50, mazda bt50, mazda cx9, mazda cx-9, '),
('http://www.mooreagolflodge.pf', 'Bienvenue sur le site de Moorea Golf Lodge', '', ''),
('http://gepasud.upf.pf', 'Présentation du Laboratoire', 'Laboratoire de Géosciences du Pacifique Sud', 'Laboratoire de Géosciences du Pacifique Sud'),
('http://www.servicedutourisme.gov.pf', 'Site du service du tourisme', 'Site officiel du tourisme en Polyn&#233;sie', 'Tahiti,Polynésie française,tourisme,statistique,tourism statistics,croisière,sites touristiques,aménagements touristiques,fréquentation touristique,réglementation,hôtels,pensions de famille,hébergement hôtelier'),
('http://www.cnps.pf', 'CNPS - Chantier Naval du Pacifique Sud - Bienvenue', 'Site de conception et r', 'chantier,naval,pacifique,polyn'),
('http://www.labotp.pf', 'Laboratoire des Travaux Publics de Polynésie française | ', ' | ', ''),
('http://www.mahina.pf', 'Mahina, ville d&#039;Histoire ville d&#039;Avenir', '', ''),
('http://www.jcm.pf', 'JCM Immobilier - 1ère agence immobilière en Polynésie Française', '', ''),
('http://www.ftvaa.pf', 'Accueil', 'Le va\'a en polynésie française', ''),
('http://www.sistra.pf', 'Accueil - SISTRA', '', ''),
('http://www.seac.pf', ' Accueil - Aviation Civile', '', ''),
('http://artisanat.pf', 'Accueil - Service de l&#039;artisanat', '', ''),
('https://www.vittoria.pf', 'Vittoria Conseil', '', 'vittora conseil, vittoria tahiti, tahiti vittoria, tahiti odoo, odoo tahiti'),
('http://www.peche.pf', 'Direction des ressources marines et minières', '', ''),
('http://www.pacificfilms.pf', '', '', ''),
('http://www.iss.pf', 'ISS &mdash; Tahiti', 'ISS Website', 'ISS, Tahiti'),
('http://forum.ladepeche.pf', 'Annonces de Polynésie française : immobilier, voiture occasion, auto, moto, emploi, occasions, annonces immobilières...', '', ''),
('http://www.hawaikinuivaa.pf', '301 Moved Permanently', '', ''),
('http://www.millesime.pf', 'Millésime - La plus belle expression du vin !', 'La vinothèque de Tahiti', 'millésime, tahiti, polynesie, vin, champagnes, spiritueux, alcool'),
('http://www.spea.pf', ' Accueil - Polynésienne des eaux', '', ''),
('http://www.snes.pf', 'SNES.PF', '', ''),
('http://www.portdepapeete.pf', 'Port Autonome de Papeete | Le port de Papeete vous accueille dans ses installations portuaires lors de vos escales dans le Pacifique Sud', '', ''),
('http://www.fenua-assurances.pf', 'Accueil - Fenua Assurances', 'Fenua Assurances, société agent général ALLIANZ, dispose de 2 agences en Polynésie française offrant une gamme complète de produits et une équipe compétente à votre écoute. Fenua assurances : l\'assureur des Polynésiens avec vous de A à Z!(assurance automobile, habitation,vie, moto, bateau, particuliers, professionenels, fenua santé, prévoyance, placement, épargne et retraite', 'Fenua assurances, Allianz, Assurance tahiti, Polynésie française, assurance polynésie française, assurance auto, assurance habitation, assurance vie, meilleure assurances tahiti, assurance numéro 1 tahiti.'),
('http://www.barreau-avocats.pf', ' Accueil - Ordre des Avocats', 'administration des services de l&#039;ordre des avocats', 'Barreau de Papeete,Ordre des Avocats,avocats spécialistes,avocats tahiti,bâtonnier'),
('http://www.catholic.pf', '', '', ''),
('http://www.nanea.pf', 'Nanea - Achat, vente et location immobilière partout en Polynésie', '', ''),
('http://www.estinfo.pf', 'Est informatique &#8211; Matériel et services informatiques à Tahiti', '', ''),
('http://www.royaltikehau.pf', 'Le Royal Tikehau vous souhaite la bienvenue - Iaorana e Maeva', '', ''),
('http://www.adt.pf', 'Aéroport de Tahiti gestionnaire des aéroports : Tahiti Faa\'a, Bora Bora, Raiatea, Rangiroa. - ', '', ''),
('http://www.huahinevacance.pf', 'huahinevacance/f', '', ''),
('http://tesa.pf', 'Accueil - TESA', '', ''),
('http://www.assemblee.pf', 'Accueil - Assemblée de la Polynésie française', '', ''),
('http://www.cmmpf.pf', 'CMMPF - Centre des métiers de la mer de la Polynésie française', '', ''),
('http://www.activ-result.pf', 'ACTIV\'RESULT - Organisme de formation professionnelle à Tahiti', 'Leader en formation professionnelle et en conseil, Activ\'Result se met au service de la performance de votre entreprise.', 'activ\'result, formation professionnelle, consulting, coaching, tahiti, activ result papeete, formation tahiti'),
('http://www.tahitinuitravel.pf', 'Home - Tahiti Nui Travel', '', ''),
('http://www.ircp.pf', 'IRCP', '', ''),
('http://www.ussp.pf', 'USSP | Le site du sport scolaire polynesien', '', ''),
('http://www.tropical-piscine.pf', 'Tropical piscine - Accueil', '', ''),
('http://www.tekuratahititravel.pf', 'Tekura Tahiti Travel | Everything begins with a smile', '', ''),
('http://www.cliniquemamao.pf', 'CLINIQUE MAMAO', '', ''),
('http://www.egat.pf', 'EGAT', '', ''),
('http://www.coursbufflier.pf', 'Cours Bufflier', '', ''),
('http://www.tahititours.pf', 'Tahiti Tours | 118 ISLANDS, 5 ARCHIPELAGOS, 1 UNIQUE JOURNEY: YOURS !', '', ''),
('http://www.restaurantlemandarin.pf', '', '', ''),
('http://orp.pf', 'Observatoire des requins de Polynesie - Accueil', '', ''),
('https://www.isi.pf', 'ISI.PF &#8211; Ingénierie des Systèmes d&#039;information', '', ''),
('http://www.tauifm.pf', 'Accueil de la radio de Tahiti&nbsp; TAUI FM', 'La radio de Tahiti TAUI FM', 'TAUIFM TAUI FM RADIO TAHITI '),
('http://satnui.pf', 'satnui', 'Un site utilisant WordPress', 'satnui'),
('http://www.europassistance.pf', 'Europ Assistance Oc&eacute;anie', '', 'tahiti, french polynesia, polyn&eacute;sie franaise'),
('http://www.chequeservice.pf', 'Chèque Service', '', ''),
('http://www.yrondi.pf', 'Garrick Yrondi', '', ''),
('http://gaati.upf.pf', 'GAATI: About', 'GAATI Mathematics Research Group French Polynesia', ''),
('http://www.somac.pf', 'S.O.M.A.C. S.A.S.U. - Soci', '', ''),
('http://www.sunset-raiatea.pf', 'Sunset Beach Motel - Raiatea - Tahiti Sun Travel', '- Official Site - Situated on the west coast of Raiatea, the Sunset Beach Motel has 22 bungalows located on a huge established coconut palm grove on the beach.          ', 'Sunset Beach Motel, sunset,SNORKELING, scuba diving,RAIATEA, beach motel,, Tahiti,activities, tours,grove,lagoon, kiteboarding,kiteboard,windsurfing, French Polynesia,Uturoa, SUNSET,raiatea, Beach Resort,bungalows, waterskiing,camping, diving,4 wheel driv'),
('http://www.oecpf.pf', 'OECPF - ORGANISATION DES EXPERTS COMPTABLES DE POLYNESIE FRANCAISE', '', 'organisation, experts, comptable, polynesie francaise, polynésie, française, tahiti, auditpac, audit, expertise globale, conseil, évaluation, consolidation, gestion'),
('http://www.captahiti.pf', 'CAPTAHITI | l’équipement Hôtelier', '', ''),
('https://www.ofina.pf', 'Ofina', '', ''),
('http://www.capelec.pf', '', '', ''),
('http://www.poly-diesel.pf', 'poly-diesel engins usinages situé en polynésie française', 'POLY-DIESEL, ENGINS ET USINAGES situés dans la Z.I. de la Punaruu (Punaauia - TAHITI)', 'diesel,engin,usinage,tahiti,polynesie'),
('http://www.mana.pf', 'Vini Internet', '', ''),
('http://www.europcar.pf', 'EUROPCAR POLYNESIA - EUROPCAR POLYNESIE', '', ''),
('http://www.jamesnormanhallhome.pf', 'James Norman Hall Museum', '', ''),
('http://www.cma.pf', ' Centre des Métiers d&#039;Art', '', ''),
('http://www.servicedutravail.gov.pf', 'Site de la Direction du Travail', '', ''),
('http://www.commune-moorea.pf', 'La commune de Moorea-Maiao &#8211; Iaorana, Manava e Maeva', '', ''),
('http://simulateur.opt.pf', 'Simulation Offre Forfaits OPTIMUM', '', ''),
('http://www.petites-entreprises.pf', '', '', ''),
('http://www.ptpu.pf', 'Accueil', '', ''),
('http://dsi.upf.pf', 'La D.S.I. | Direction des Systèmes d&#039;Information', '', ''),
('http://www.service-energie.pf', 'Service énergie - Polynésie Française', '', ''),
('https://flightstatus.airtahitinui.pf', 'FLIGHT STATUS - Air Tahiti Nui', '', ''),
('http://www.tya.pf', 'Tahiti Yacht Agents | ', ' | ', ''),
('http://mathaara.math.pf', 'Math&#039;a Ara', '', ''),
('http://www.bdo.pf', '  	  	BDO POLYNESIE FRANÇAISE  | WELCOME TO BDO TAHITI WEBSITE    ', '', ''),
('http://www.bridalbeauty.pf', 'Bora Bora Bridal Beauty', 'On site Hair and Make up in Bora Bora for your wedding, photoshooting or event', 'Bora Bora Make up, Bora Bora Photo, Bora Bora Wedding, Bora bora Hair make up artist, Bora bora Hairstyle, Bora bora beauty, Bora bora bridal beauty, Bora bora honeymoon, Tahiti hair, tahiti beauty, tahiti honeymonn, tahiti make up, tahiti wedding'),
('http://www.mormonmedia.org.pf', 'Salle de presse – Église de Jésus-Christ des Saints des Derniers Jours', '', ''),
('http://wml.mana.pf', 'Webmail MANA', '', ''),
('http://dane.monvr.pf', 'La DANE - DANE', '', ''),
('http://www.urbanisme.gov.pf', 'Site du Service de l\'urbanisme', '', ''),
('http://www.polypneus.pf', 'Polypneus, Polypneus, ', 'website description', 'keyword1, keywords2'),
('https://www.fenuaresident.pf', 'fenuaresident.pf', '', ''),
('http://www.fgc.pf', 'Fédération Générale du Commerce', 'FGC Tahiti- Syndicat des Commerçants', ''),
('https://eservices.mana.pf', 'Mana e-Services', '', ''),
('http://www.seo.pf', 'Histoire de la Polynésie Orientale | Société Etudes Océaniennes', 'La Société des Etudes Océaniennes étudie toutes les questions se rattachant à l\\&#039;histoire et les institutions, moeurs coutumes et traditions des Maoris de', 'études océaniennes, histoire de la polynésie, moeurs et coutumes maori, moeurs de la polynésie, coutumes de la polynésie, archives polynésie'),
('http://www.archives.pf', 'Te Piha Faufa&#039;a Tupuna &raquo; Service du Patrimoine Archivistique et Audiovisuel', '', ''),
('http://www.greenlodge.pf', 'Green Lodge - bungalows de luxe', 'Le confort de 6 unités de luxe, construites au bord de l’eau, sur un site qui possède le charme des Tuamotu. Posé sur la plage, comme dans un tableau...', '');

--
-- Index pour les tables exportées
--
